CREATE DATABASE donate4;
USE donate4;



CREATE TABLE shirts (
id INT NOT NULL AUTO_INCREMENT,
BRAND VARCHAR(255) NOT NULL ,
COLOR VARCHAR(255) NOT NULL ,
SIZE  VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);


CREATE TABLE pants (
id INT AUTO_INCREMENT NOT NULL ,
BRAND VARCHAR(255) NOT NULL ,
COLOR VARCHAR(255) NOT NULL ,
SIZE  VARCHAR(255) NOT NULL ,
PRIMARY KEY (id)
);


CREATE TABLE shoes (
id INT AUTO_INCREMENT NOT NULL ,
BRAND VARCHAR(255) NOT NULL ,
COLOR VARCHAR(255) NOT NULL ,
SIZE  VARCHAR(255) NOT NULL ,
PRIMARY KEY (id)
);