CREATE DATABASE donate;
USE donate;



CREATE TABLE T-Shirts (
`T-ShirtsID` INT NOT NULL AUTO_INCREMENT,
`BRAND` VARCHAR(255) NOT NULL ,
`COLOR` VARCHAR(255) NOT NULL ,
`SIZE`  CHAR(1) NOT NULL,
`donated_at` DATE ,
PRIMARY KEY (`T-ShirtsID`)
);


CREATE TABLE pants (
`Pants-ID` INT AUTO_INCREMENT NOT NULL ,
`BRAND` VARCHAR(255) NOT NULL ,
`COLOR` VARCHAR(255) NOT NULL ,
`SIZE`  VARCHAR(255) NOT NULL ,
`donated_at` DATE ,

PRIMARY KEY (`Pants-ID`)
);


CREATE TABLE shoes (
`shoes-ID` INT AUTO_INCREMENT NOT NULL ,
`BRAND` VARCHAR(255) NOT NULL ,
`COLOR` VARCHAR(255) NOT NULL ,
`GENDER` VARCHAR(255) NOT NULL ,
`SIZE`  VARCHAR(255) NOT NULL ,
`donated_at` DATE ,

PRIMARY KEY (`shoes-ID`)
);
